import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import QueryProvider from "@/components/query-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Theme accentColor="plum" grayColor="olive" radius="full" scaling="95%">
          <QueryProvider>{children}</QueryProvider>
          <Toaster position="top-center" />
        </Theme>
      </body>
    </html>
  );
}
