import { Chat } from "@/types/chats";
import { User } from "@/types/user";

export const currentUser: User = {
  id: "patient123",
  image: "/logo.svg",
  email: "patient123@example.com",
  firstname: "Patient",
  lastname: "Sick",
  username: "patient123",
};

export const mockChats: Chat[] = [
  {
    id: "judfhdfd",
    createdAt: "2023-10-27T10:00:00.000Z",
    creatorId: "patient123",
    account_type: "patient",
    professional: {
      id: "doctor456",
      name: "Dr. Emily Carter",
      avatar: "/logo.svg",
      field: "General Practitioner",
      phoneNumber: "555-123-4567",
      email: "emily.carter@exampleclinic.com",
    },
    content: {
      lastMessage: {
        id: "msg789",
        sentBy: "patient123",
        senderAccountType: "patient",
        createdAt: "2023-10-27T10:00:00.000Z",
        deleted: false,
        deletedAt: null,
        text: "Hello, Dr. Carter, I've been experiencing persistent headaches and fatigue for the past few weeks.",
        pdf: null,
        image: null,
        audio: null,
        video: null,
        file: null,
      },
      messages: [
        {
          id: "msg123",
          sentBy: "patient123",
          senderAccountType: "patient",
          createdAt: "2023-10-27T10:00:00.000Z",
          deleted: false,
          deletedAt: null,
          text: "Hello, how are you?",
          pdf: null,
          image: null,
          audio: null,
          video: null,
          file: null,
        },
        {
          id: "msg456",
          sentBy: "doctor456",
          senderAccountType: "professional",
          createdAt: "2023-10-27T10:02:00.000Z",
          deleted: false,
          deletedAt: null,
          text: "Hello! I'm doing well, thank you. How can I assist you today?",
          pdf: null,
          image: null,
          audio: null,
          video: null,
          file: null,
        },
        {
          id: "msg789",
          sentBy: "patient123",
          senderAccountType: "patient",
          createdAt: "2023-10-27T10:03:00.000Z",
          deleted: false,
          deletedAt: null,
          text: "Hello, Dr. Carter, I've been experiencing persistent headaches and fatigue for the past few weeks.",
          pdf: null,
          image: null,
          audio: null,
          video: null,
          file: null,
        },
        {
          id: "msg1011",
          sentBy: "doctor456",
          senderAccountType: "professional",
          createdAt: "2023-10-27T10:05:00.000Z",
          deleted: false,
          deletedAt: null,
          text: "I see. Can you describe the headaches? Are they throbbing, constant, or sharp? And where exactly do you feel them?",
          pdf: null,
          image: null,
          audio: null,
          video: null,
          file: null,
        },
        {
          id: "msg1213",
          sentBy: "patient123",
          senderAccountType: "patient",
          createdAt: "2023-10-27T10:07:00.000Z",
          deleted: false,
          deletedAt: null,
          text: "They're more of a constant, dull ache, mostly in my forehead and temples. The fatigue is also pretty bad; I'm having trouble focusing.",
          pdf: null,
          image: null,
          audio: null,
          video: null,
          file: null,
        },
        {
          id: "msg1415",
          sentBy: "doctor456",
          senderAccountType: "professional",
          createdAt: "2023-10-27T10:10:00.000Z",
          deleted: false,
          deletedAt: null,
          text: "Okay. And have you noticed any other symptoms, such as changes in vision, nausea, or dizziness? Also, are you experiencing any stress or changes in your sleep patterns?",
          pdf: null,
          image: null,
          audio: null,
          video: null,
          file: null,
        },
      ],
    },
  },
];
